feat : Implemented Games page according to design
iiitv/arcadia-official-web pull request #11
Opened 2021-10-04 06:34 UTC by siddhantsingh186

Fixes #6  Make Login Page

2021-10-04 15:59 UTC, siddhantsingh186 commented
> @siddhantsingh186 you mentioned wrong issue here ig.

Sorry, my bad! I have updated the PR comment with the correct issue.

2021-10-05 05:34 UTC, prathmeshkhandelwal1 commented
Can you add proper Screen shot of pages, as we don't have any netlify preview here.

2021-10-05 06:00 UTC, siddhantsingh186 commented
> Can you add proper Screen shot of pages, as we don't have any netlify preview here.

Sure
![games2](https://user-images.githubusercontent.com/54211359/135968674-f5685d49-b92b-4890-9554-09f8577f6f00.png)
![games1](https://user-images.githubusercontent.com/54211359/135968680-0e6ecb24-e399-4bff-952b-3c815e6e3f7c.png)
![games3](https://user-images.githubusercontent.com/54211359/135968687-388b9de1-ba00-4b40-b1e7-4b7ab1882e1b.png)
.

2021-10-05 12:49 UTC, prathmeshkhandelwal1 requested changes

2021-10-05 12:49 UTC, prathmeshkhandelwal1 commented on src/components/games/Games.js
> +            <img className = "games__cards__top__csgo" alt = "" src = "images/CSGO.png" ></img>
Formatting error.

2021-10-05 12:49 UTC, prathmeshkhandelwal1 commented on src/components/games/Games.js
> +            <img className = "games__cards__bottom__assassins" alt = "" src = "images/assasin.png" ></img>
here also

2021-10-05 12:49 UTC, prathmeshkhandelwal1 commented on src/components/games/Games.js
> +            <img className = "games__cards__top__csgo" alt = "" src = "images/CSGO.png" ></img>
Use self closing img tag here.

2021-10-05 14:52 UTC, siddhantsingh186 commented
@prathmeshkhandelwal1 requested changes are done in the latest commit.

2021-10-05 15:09 UTC, prathmeshkhandelwal1 commented
> @prathmeshkhandelwal1 requested changes are done in the latest commit.

Conflicts are remaining, this arises due the merge of another pr by akshat, can you resolve that please.

2021-10-05 15:29 UTC, siddhantsingh186 commented
> > @prathmeshkhandelwal1 requested changes are done in the latest commit.
> 
> Conflicts are remaining, this arises due the merge of another pr by akshat, can you resolve that please.

Done👍

2021-10-05 15:31 UTC, merged